name = "count"
signature = "count(input: any, window: window = null) -> u32"
short_doc = "Counts each new, non-`null` value in the input."
long_doc = """
### Parameters
* input: The input to be counted.
* window: The window to aggregate within, as described in
[Aggregation Functions](#aggregation-functions). If `null`, aggregates are across all
rows for the current entity. If non-`null`, aggregates are within the specified window.
See [window functions](#window-functions) for how to specify the aggregation window.

### Results
For each input row, return the count of new, non-`null` rows in `input` up to and
including the input row for the given entity. Returns `0` if there have been no
such inputs.
"""
tags = ["aggregation"]

[[examples]]
name = "Count"
expression = "count(Input.value)"
input_csv = """
time,key,value
2021-01-01T00:00:00.000000000Z,Ben,50.7
2021-01-02T00:00:00.000000000Z,Ryan,
2021-01-02T00:00:00.000000000Z,Ryan,67.2
2021-01-03T00:00:00.000000000Z,Ben,1.2
2021-01-04T00:00:00.000000000Z,Ben,
2021-01-05T00:00:00.000000000Z,Ryan,2.3
"""
output_csv = """
time,key,value,result
2021-01-01T00:00:00.000000000,Ben,50.7,1
2021-01-02T00:00:00.000000000,Ryan,,0
2021-01-02T00:00:00.000000000,Ryan,67.2,1
2021-01-03T00:00:00.000000000,Ben,1.2,2
2021-01-04T00:00:00.000000000,Ben,,2
2021-01-05T00:00:00.000000000,Ryan,2.3,2
"""
