
= Engine and manager logs 

The Kaskada engine and manager generate logs that can be used to troubleshoot issues with the Kaskada system. 
These logs contain valuable information about the state of the system and can be used to diagnose issues. 
Including relevant segments from the logs when you open an issue can greatly help others troubleshoot your problem.


Log files are located in the user's home folder `~/.cache/kaskada/logs`. 
For each of the services (engine and manager), a standard output log and standard error log are created prefixed by the launch timestamp.

Here is an example with two separate runs of the engine and manager.


....
/home/therapon/.cache/kaskada/logs
├── 2023-05-03T15-53-45-engine-stderr.log
├── 2023-05-03T15-53-45-engine-stdout.log
├── 2023-05-03T15-53-45-manager-stderr.log
├── 2023-05-03T15-53-45-manager-stdout.log
├── 2023-05-04T12-12-33-engine-stderr.log
├── 2023-05-04T12-12-33-engine-stdout.log
├── 2023-05-04T12-12-33-manager-stderr.log
├── 2023-05-04T12-12-33-manager-stdout.log
....

The standard output log contains the output of the application (info, warn etc.) and the standard error log contains any errors that occurred during the run.

[TIP]
====
On Unix systems the `tail` command is very convenient for viewing the last few lines of multiple files at a time. 
For example, to view new lines of the standard output logs for the engine and manager you can run the following command from the logs folder:
`tail -f <timestamp>-engine-stdout.log <timestamp>-engine-stderr.log`
====
