_extends: kaskada:.github/release-drafter.yml

name-template: Python $RESOLVED_VERSION
tag-template: python@v$RESOLVED_VERSION
tag-prefix: python@v

# Only include PRs with one of these labels
include-labels:
  - python