FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main 

# install go 
RUN curl -OL https://go.dev/dl/go1.19.7.linux-amd64.tar.gz && \
    tar -C /usr/local/ -xzf go1.19.7.linux-amd64.tar.gz 

ENV PATH="$PATH:/usr/local/go/bin:/root/go/bin"

RUN go install github.com/onsi/ginkgo/v2/ginkgo@v2.1.4