# Image to cross compile our go code from linux/amd64 to linux/arm64

FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main 

#install go 
RUN curl -OL https://go.dev/dl/go1.19.7.linux-amd64.tar.gz && \
    tar -C /usr/local/ -xzf go1.19.7.linux-amd64.tar.gz 

ENV PATH="$PATH:/usr/local/go/bin:/root/go/bin"

# RUN go install github.com/onsi/ginkgo/v2/ginkgo@v2.1.4

# ENV CGO_ENABLED=1 \
#     GOOS=linux \
#     GOARCH=arm64 \
#     CC="$CC_aarch64_unknown_linux_gnu" \
#     CXX="$CXX_aarch64_unknown_linux_gnu"