{{ if .Values.auth.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kaskada-canary.serviceAccountName" . }}
  namespace: {{ include "kaskada-canary.namespace" . }}
  labels:
    {{- include "kaskada-canary.labels" . | nindent 4 }}
  {{- with .Values.auth.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.auth.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}