= Installing Kaskada

== Using Kaskada with Python

.Installing Kaskada using pip
[,shell]
----
pip install kaskada 
----

[NOTE]
.Pip and pip3 
====
Depending on you Python installation and configuration you may have `pip3` instead of `pip` available in your terminal. 
If you do have `pip3` replace `pip` with `pip3` in your command, i.e., `pip3 install kaskada`
====

Kaskada is now installed. Kaskada can be used locally by creating a local session.

.Creating a local Kaskada session in Python
[.python]
----
from kaskada.api.session import LocalBuilder
session = LocalBuilder().build()
----

Creating a local session will download and run the Kaskada service, and configure the client to use the local endpoint.


== Using Kaskada with IPython (Jupyter)

IPython is an interactive Python runtime used by Jupyter and other
notebooks to evaluate Python code blocks. IPython supports "magic
extensions" for customizing how code blocks are interpreted. Kaskada
provides a magic extension that simplifies querying Kaskada. 

Kaskada's python library includes notebook customizations that allow us to write queries in the Fenl language but also receive and render the results of our queries in our notebooks. 
We need to enable these customizations first before we can use them. 

.Enable fenlmagic in this notebook 
[,python]
----
%load_ext fenlmagic
----

This will load the extension into the IPython context. You can verify
the install worked by initializing the extension:

[source,ipython]
----
%%fenl?
----

[source,bash]
----
  %fenl [--as-view AS_VIEW] [--data-token DATA_TOKEN] [--debug DEBUG]
            [--output OUTPUT] [--preview-rows PREVIEW_ROWS]
            [--result-behavior RESULT_BEHAVIOR] [--var VAR]

fenl query magic

optional arguments:
  --as-view AS_VIEW     adds the body as a view with the given name to all
                        subsequent fenl queries.
  --data-token DATA_TOKEN
                        A data token to run queries against. Enables
                        repeatable queries.
  --debug DEBUG         Shows debugging information
  --output OUTPUT       Output format for the query results. One of "df"
                        (default), "json", "parquet" or "redis-bulk". "redis-
                        bulk" implies --result-behavior "final-results"
  --preview-rows PREVIEW_ROWS
                        Produces a preview of the data with at least this many
                        rows.
  --result-behavior RESULT_BEHAVIOR
                        Determines which results are returned. Either "all-
                        results" (default), or "final-results" which returns
                        only the final values for each entity.
  --var VAR             Assigns the QueryResponse to a local variable with the given
                        name. The QueryResponse contains result_url, query and dataframe. 
----