[package]
name = "fenl-fiddle"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
derive_more = "0.99.17"
futures = "0.3.27"
parquet = { version = "40.0.0", features = ["async"] }
prettytable-rs = "0.10.0"
tauri = { version = "1.4", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sparrow-api = { path = "../../crates/sparrow-api" }
sparrow-compiler = { path = "../../crates/sparrow-compiler"}
sparrow-runtime = { path = "../../crates/sparrow-runtime" }
sparrow-qfr = { path = "../../crates/sparrow-qfr" }
error-stack = { version = "0.3.1", features = ["anyhow", "spantrace"] }
tempfile = "3.4.0"
uuid = { version = "1.3.0", features = ["v4"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
