[package]
name = "sparrow-testing"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = """
Testing utilities for Sparrow.
"""

[dependencies]
arrow-array.workspace = true
arrow-csv.workspace = true
arrow-json.workspace = true
arrow-schema.workspace = true
arrow-select.workspace = true
derive_more.workspace = true
error-stack.workspace = true
itertools.workspace = true
parquet.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tracing-error.workspace = true
tracing-subscriber.workspace = true

[lib]
doctest = false
