= Client Installation 

== Python Client

The Kaskada Python client can be installed using `pip`

[source,bash]
----
pip install kaskada 
----

This will download and install the latest stable Kaskada library.

== IPython (Jupyter) Extension

IPython is an interactive Python runtime used by Jupyter and other
notebooks to evaluate Python code blocks. IPython supports "magic
extensions" for customizing how code blocks are interpreted. Kaskada
provides a magic extension that simplifies querying Kaskada. To use the
extension you must first install the `fenlmagic` python package, for
example using `pip`:

[source,bash]
----
pip install fenlmagic
----


NOTE: Make sure to install this package in the same environment IPython will be running in.


Inside an IPython session (for example a Jupyter notebook) the extension
can be loaded using the magic command `%load_ext`:

[source,ipython]
----
%load_ext fenlmagic
----

This will load the extension into the IPython context. You can verify
the install worked by initializing the extension:

[source,ipython]
----
%%fenl?
----

[source,bash]
----
  %fenl [--as-view AS_VIEW] [--data-token DATA_TOKEN] [--debug DEBUG]
            [--output OUTPUT] [--preview-rows PREVIEW_ROWS]
            [--result-behavior RESULT_BEHAVIOR] [--var VAR]

fenl query magic

optional arguments:
  --as-view AS_VIEW     adds the body as a view with the given name to all
                        subsequent fenl queries.
  --data-token DATA_TOKEN
                        A data token to run queries against. Enables
                        repeatable queries.
  --debug DEBUG         Shows debugging information
  --output OUTPUT       Output format for the query results. One of "df"
                        (default), "json", "parquet" or "redis-bulk". "redis-
                        bulk" implies --result-behavior "final-results"
  --preview-rows PREVIEW_ROWS
                        Produces a preview of the data with at least this many
                        rows.
  --result-behavior RESULT_BEHAVIOR
                        Determines which results are returned. Either "all-
                        results" (default), or "final-results" which returns
                        only the final values for each entity.
  --var VAR             Assigns the QueryResponse to a local variable with the given
                        name. The QueryResponse contains result_url, query and dataframe. 
----
