project:
  type: website
  output-dir: _site
  preview:
    port: 4200

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  favicon: "_static/favicon.png"
  google-analytics: G-HR9E2E6TG4
  navbar:
    background: white
    logo: _static/kaskada-negative.svg
    logo-alt: "Kaskada logo."
    title: false
    left:
      - href: guide/index.qmd
        text: User Guide
      - href: examples/index.qmd
        text: Examples
      - href: reference/index.qmd
        text: API
      - href: blog/index.qmd
        text: Blog
    right:
      - icon: slack
        href: https://join.slack.com/t/kaskada-hq/shared_invite/zt-1t1lms085-bqs2jtGO2TYr9kuuam~c9w
      - icon: github
        href: https://github.com/kaskada-ai/kaskada
  page-footer:
    border: true
    left: "© Copyright 2023, Kaskada Contributors."
  repo-url: https://github.com/kaskada-ai/kaskada/
  repo-subdir: python/source
  repo-actions: "edit"
  site-url: https://kaskada.io/kaskada
  title: Kaskada

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/kaskada\.io\/'

