project:
  type: website
  output-dir: _site
  preview:
    port: 4200

#metadata-files:
#  - reference/_sidebar.yml

website:
  favicon: "_static/favicon.png"
  google-analytics: G-HR9E2E6TG4
  page-navigation: true
  navbar:
    background: primary
    logo: "_static/kaskada-negative.svg"
    logo-alt: "Kaskada logo."
    title: false
    left:
      - href: guide/index.qmd
        text: User Guide
      - href: examples/index.qmd
        text: Examples
      - href: reference/index.qmd
        text: API
      - href: blog/index.qmd
        text: Blog
    right:
      - icon: slack
        href: https://join.slack.com/t/kaskada-hq/shared_invite/zt-1t1lms085-bqs2jtGO2TYr9kuuam~c9w
      - icon: github
        href: https://github.com/kaskada-ai/kaskada
  sidebar:
  - title: User Guide
    style: docked
    contents: guide
  - title: Examples
    contents: examples
  - title: API
    style: docked
    contents: reference

  page-footer:
    border: true
    left: "© Copyright 2023, Kaskada Contributors."
  repo-url: https://github.com/kaskada-ai/kaskada/
  repo-subdir: python/source
  repo-actions:
    - edit
    - source
  site-url: https://kaskada.io/kaskada
  title: Kaskada

format:
  html:
    theme:
      light: flatly
      dark: darkly #vapor
    css:
      - styles.css
      - design-style.css
    include-in-header: _announcement.html
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/kaskada\.io\/'

filters:
  - interlinks

interlinks:
  fast: true
  sources:
    numpy:
      url: https://numpy.org/doc/stable/
    pandas:
      url: https://pandas.pydata.org/docs/
    pyarrow:
      url: https://arrow.apache.org/docs/
    python:
      url: https://docs.python.org/3/

