quartodoc:
  title: API
  dir: reference
  out_index: index.qmd
  parser: google
  package: kaskada
  renderer:
    style: _renderer.py
  render_interlinks: true
  options:
    children: separate
  sidebar: "ref/sidebar.yml"

#  # write sidebar data to this file
#  sidebar: reference/_sidebar.yml

  sections:
    - title: kaskada
      contents:
        - Arg
        - LiteralValue
        - Timestream
        - windows
        - sources



    # - title: Windows
    #   package: kaskada.windows

    # - title: Sources
    #   options:
    #     children: embedded
    #   package: kaskada.sources

        # - Source
        # - CsvString
        # - JsonlString
        # - Pandas
        # - Parquet
        # - PyDict
    # - title: Destinations
    #   options:
    #     children: separate
    #   contents:
    #     - destinations
    # - title: Results
    #   desc: "boop"
    #   package: kaskada.results
    #   contents:
    #     - name: History
    #       children: linked
    #     - name: Snapshot
    #       children: separate
    # - title: Execution
    #   options:
    #     children: separate
    #   contents:
    #     - Execution
    #     - ResultIterator
