---
title: Aggregation
---

The User Guide has details on [aggregations in general](../guide/aggregation.qmd).

::: {.callout-important}
It is important to remember that aggregations are partitioned by entity and windowed, with the default behavior being cumulative up to the current time.
:::


| Method                                               | Description                                                                 |
|------------------------------------------------------|-----------------------------------------------------------------------------|
| [Timestream.collect](`kaskada.Timestream.collect`)   | Return a Timestream collecting up to the last `max` values in the `window`. |
| [Timestream.count](`kaskada.Timestream.count`)       | Return a Timestream containing the count value in the `window`.             |
| [Timestream.count_if](`kaskada.Timestream.count_if`) | Return a Timestream containing the count of `true` values in `window`.      |
| [Timestream.first](`kaskada.Timestream.first`)       | Return a Timestream containing the first value in the `window`.             |
| [Timestream.last](`kaskada.Timestream.last`)         | Return a Timestream containing the last value in the `window`.              |
| [Timestream.max](`kaskada.Timestream.max`)           | Return a Timestream containing the max value in the `window`.               |
| [Timestream.mean](`kaskada.Timestream.mean`)         | Return a Timestream containing the mean value in the `window`.              |
| [Timestream.min](`kaskada.Timestream.min`)           | Return a Timestream containing the min value in the `window`.               |
| [Timestream.stddev](`kaskada.Timestream.stddev`)     | Return a Timestream containing the standard deviation in the `window`.      |
| [Timestream.sum](`kaskada.Timestream.sum`)           | Return a Timestream summing the values in the `window`.                     |
| [Timestream.variance](`kaskada.Timestream.variance`) | Return a Timestream containing the variance in the `window`.                |