= Hello World (CLI)

== Installation

To use Kaskada on the command line, you'll need to install three components:

* The Kaskada command-line executable
* The Kaskada manager, which serves the Kaskada API
* The Kaskada engine, which executes queries

Each Kaskada release has pre-compiled binaries for each component. 
You can visit the https://github.com/kaskada-ai/kaskada/releases[Releases] page on Github to obtain the latest Kaskada release version binaries for your platform.
The example commands below will download the latest Kaskada binaries and applies to Linux and OSX.


[source,shell]
----
curl -s https://api.github.com/repos/kaskada-ai/kaskada/releases/latest |\
grep "browser_download_url.*" |\
grep $(uname -m | sed 's/x86_64/amd64/') |\
grep $(uname -s | tr '[:upper:]' '[:lower:]') |\
cut -d ':' -f2,3 |\ 
tr -d \" |\ 
xargs -I {} sh -c 'curl -L {} -o $(basename {}| cut -d '-' -f1,2)'


chmod +x kaskada-*
----

[TIP]
.Authorizing applications on OSX
====
If you're using OSX, you may need to unblock the applications.
OSX prevents applications you download from running as a security feature.
You can remove the block placed on the file when it was downloaded with the following command:

[source,shell]
----
xattr -dr com.apple.quarantine <path to file>
----
====

You can start a local instance of the Kaskada service by running the manager and engine:

[source,shell]
----
./kaskada-manager 2>&1 > manager.log 2>&1 &
./kaskada-engine serve > engine.log 2>&1 &
----

[TIP]
.Allowing services to listen on OSX
----
When using OSX, you may need to allow these services to create an API listener the first time you run these commands.
This is normal, and indicates the services are working as expected - the API allows services to communicate between themselves.
----

To verify they're installed correctly and executable, try running the following command (which lists any resources you've created):

[source,shell]
----
./kaskada-cli sync export --all
----

You should see output similar to the following:

[source,shell]
----
10:18AM INF starting export
{}  
10:18AM INF Success!
----


== Managing resources

The CLI manages Kaskada resources declaratively by managing spec files. 
A spec file is a YAML file describing a set of Kaskada resources, for examples tables and views.

We'll begin by creating a table.
The first step is to create a spec file containing the table's definition.

When creating a table, you must provide some information about how each
row should be interpreted. You must describe:

* A field containing the time associated with each event
(`time_column_name`). The time should refer to when the event occurred.
* An initial xref:fenl:entities.adoc[entity] key associated with each row
(`entity_key_column_name`). The entity should identify a _thing_ in the
world that each event is associated with. Don't worry too much about
picking the "right" value here - it's easy to change the entity key in
Fenl.
* An (optional) subsort column associated with each event (`subsort_column_name`).
This value is used to order rows associated with the same time value.

For more information about these fields, see:
xref:ROOT:loading-data.adoc#file-format[Expected File Format]

[source,yaml]
.spec.yaml
----
tables:
  # The name of the table
- tableName: Purchase               

  # A field containing the time associated with each event
  timeColumnName: purchase_time     

  # An initial entity key associated with each event
  entityKeyColumnName: customer_id  

  # Where the table's data will be stored
  # The default storage location is 'kaskada', and uses local files to store events.
  source:                          
    kaskada: {}
----

To create this table, we must sync the state of the Kaskada service with the contents of the file.

[source,shell]
----
./kaskada-cli sync apply -f spec.yaml

# > 2:18PM INF starting plan
# > 2:18PM INF resource not found on system, will create it kind=*kaskadav1alpha.Table name=GamePlay
# > 2:18PM INF resource not found on system, will create it kind=*kaskadav1alpha.Table name=Purchase
# > 2:18PM INF Success!
----

This creates a table named `Purchase`. Any data loaded into this table
must have a timestamp field named `purchase_time`, a field named
`customer_id`, and a field named `subsort_id`.

[TIP]
.Idiomatic Kaskada
====
We like to use CamelCase to name tables because it
helps distinguish data sources from transformed values and function
names.
====

You've now created your first table! 

== Loading Data

Now that we've created a table, we're ready to load some data into it.

Data can be loaded into a table in multiple ways. In this example we'll
load the contents of a Parquet file into the table. To learn about
the different ways data can be loaded into a table, see the
xref:developing:tables.adoc#uploading-data["Uploading Data"
section of the "Tables"] page.

[source,shell]
----
curl -L "https://drive.google.com/uc?export=download&id=1SLdIw9uc0RGHY-eKzS30UBhN0NJtslkk" -o purchase.parquet

./kaskada-cli load \
    --table Purchase \
    --file-path file://${PWD}/purchase.parquet
----

The file's content is added to the table.

For more help with tables and loading data, see xref:developing:tables.adoc[Reference -
Tables]

== Querying Data

You can write queries in a number of ways with Kaskada. As you are
iterating it can be helpful to build up your queries as components
as you go.  Once you'd like to persist a query, check out our
article on sharing queries with xref:developing:views.adoc[Views].

Let's start by looking at the Purchase table without any filters, this
query will return all of the columns and rows contained in a table:

[source,shell]
----
./kaskada-cli query run --stdout --response-as csv <<EOS
Purchase
EOS
----

[NOTE]
====
This table is intentionally small so that you can get to know queries with Kaskada. 
When working with larger data sets, you may want to write the results to a file rather than `stdout` (by omitting the `--stdout` flag).
====

Let's walk through this command.
We begin by using the CLI to run a query: `kaskada-cli query run`.
CLI commands are organized into groups like `query`, `load`, and `sync` - each group contains a set of related sub-commands.
In order to see the results of our query, we used the command flag `--stdout`; the default behavior is to write results to a file and return a JSON object describing the result of the query.
Finally, we specified how to encode the results with the flag `--response-as csv`.
CSV is a good format for writing results to STDOUT, but the default is to encode results in Parquet, which is a much more efficient encoding for larger datasets.
The query is enclosed between `<<EOS` and `EOS` - this is Bash syntax for "heredocs", which allow you to easily write multi-line strings and pass them into the CLI on STDIN.


It can be helpful to limit your results to a single entity.
This makes it easier to see how a single entity changes over time.

[source,shell]
----
./kaskada-cli query run --stdout --response-as csv <<EOS
Purchase | when(Purchase.customer_id == "patrick")
EOS
----

As you begin to better understand your data you can start using
aggregations over your data such as the `max()` function:

[source,shell]
----
./kaskada-cli query run --stdout --response-as csv <<EOS
{
   max_purchase: Purchase.amount | max(),
} | when(Purchase.customer_id == "patrick")
EOS
----

[IMPORTANT]
====
These results may be surprising if you were expecting a single value,
this is a feature, not a bug!

Computations in Fenl are temporal: they produce a time-series of values
describing the full history of a computation's results. Temporal
computation allows Fenl to capture what an expression's value would have
been at arbitrary times in the past.

Fenl values can time-travel forward through time. Time travel allows
combining the result of different computations at different points in
time. Because values can only travel forward in time, Fenl prevents
information about the future from "leaking" into the past.

Read more in the xref:fenl:language-guide.adoc[Fenl
Language Guide]
====

Now we can start building up more complex queries. To reduce the set of columns
output in your query, you can define a record with the curly braces
`{ }` and name the columns with a label shown on the left of the `:` in
the below query. In order to debug your features, we recommend including
the time and the entity with each query so that you can walk through the
results in time:

[source,shell]
----
./kaskada-cli query run --stdout --response-as csv <<EOS
{
    time: Purchase.purchase_time,
    entity: Purchase.customer_id,
    max_amount: Purchase.amount | max(),
    min_amount: Purchase.amount | min(),
} | when(Purchase.customer_id == "patrick")
EOS
----

For more help writing queries, see xref:developing:queries.adoc[Reference -
Writing Queries]
