---
title: Arithmetic
---

Timestreams support a variety of arithmetic operations.

::: {.callout-important}
In addition to the chainable methods, standard operators are implemented where appropriate.
For instance, `a.add(b)` may be written as `a + b`.
See the notes on the specific functions for more information.
:::


| Method                                               | Description                                                                   |
|------------------------------------------------------|-------------------------------------------------------------------------------|
| [Timestream.add](`kaskada.Timestream.add`)           | Return a Timestream adding this and `rhs`.                                    |
| [Timestream.ceil](`kaskada.Timestream.ceil`)         | Return a Timestream rounding self up to the next largest integer.             |
| [Timestream.clamp](`kaskada.Timestream.clamp`)       | Return a Timestream from `self` clamped between `min` and `max`.              |
| [Timestream.div](`kaskada.Timestream.div`)           | Return a Timestream by dividing this and `divisor`.                           |
| [Timestream.exp](`kaskada.Timestream.exp`)           | Return a Timestream raising `e` to the power of `self`.                       |
| [Timestream.floor](`kaskada.Timestream.floor`)       | Return a Timestream of self rounded down to the nearest integer.              |
| [Timestream.greatest](`kaskada.Timestream.greatest`) | Return a Timestream with the maximum value of `self` and `rhs` at each point. |
| [Timestream.least](`kaskada.Timestream.least`)       | Return a Timestream with the minimum value of `self` and `rhs` at each point. |
| [Timestream.mul](`kaskada.Timestream.mul`)           | Return a Timestream multiplying this and `rhs`.                               |
| [Timestream.neg](`kaskada.Timestream.neg`)           | Return a Timestream from the numeric negation of self.                        |
| [Timestream.powf](`kaskada.Timestream.powf`)         | Return a Timestream raising `self` to the power of `power`.                   |
| [Timestream.round](`kaskada.Timestream.round`)       | Return a Timestream with all values rounded to the nearest integer.           |
| [Timestream.sqrt](`kaskada.Timestream.sqrt`)         | Return a Timestream with the square root of all values.                       |
| [Timestream.sub](`kaskada.Timestream.sub`)           | Return a Timestream subtracting `rhs` from this.                              |