from typing import Sequence

class Session:
    def __init__(self) -> None: ...
    def table_names(self) -> list[str]: ...
    def add_table(self, str): ...

class Expr:
    def __init__(
        self, function: str, args: Sequence[Expr | int | float | str]
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def data_type_string(self) -> str: ...
