# TODO: Use Makefile provided in CI (might have to move to docker builds in CI or drop docker in Makefile)
# TODO: Move ent generation out of build jon. Tried but something was off with cacing and builds would fail
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  merge_group:
    branches: [ main ]

# In cases of concurrent workflows running (consecutive pushes to PR)
# leave the latest workflow and cancel the other (older) workflows
# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Notebook Examples CI

jobs:
  verify_notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
