# Maintain draft releases based on changes.

name: Update draft releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  engine_draft:
    runs-on: ubuntu-latest
    concurrency:
      group: engine-release
    steps:
      - name: Draft Engine release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-engine.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  python_client_draft:
    runs-on: ubuntu-latest
    concurrency:
      group: python-client-release
    steps:
      - name: Draft Python Client release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-python-client.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  python_draft:
    runs-on: ubuntu-latest
    concurrency:
      group: python-release
    steps:
      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-python.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}