# Maintain draft releases based on changes.

name: Update draft releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  python_draft:
    runs-on: ubuntu-latest
    concurrency:
      group: python-release
    steps:
      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}